### ISSUE TITLE
--p-where warn when column is not found and when empty table

### ISSUE THREAD

**Issue by antgonza** [qiime2/q2-feature-table#154]
Not sure if this issue goes here, I found the issue in `feature-table filter-samples`  or somewhere else where --p-where comes from.

Anyway, if I filter a table using a column that doesn't exist it works and returns an empty table, which IMOO should be a warning/error.

Example:
```bash
$ curl -sL "https://data.qiime2.org/2017.10/tutorials/moving-pictures/sample_metadata.tsv" > "sample-metadata.tsv"
$ curl -o table.qza https://docs.qiime2.org/2017.10/data/tutorials/moving-pictures/table-deblur.qza

$ qiime feature-table filter-samples \
   --m-metadata-file sample-metadata.tsv \
   --i-table  table.qza \
   --p-where "'this_doesnt_exist' == 'FALSE'" \
   --o-filtered-table out.qza
Saved FeatureTable[Frequency] to: out.qza
```

**Comment by thermokarst** [comment]
I like that plan, but this example isn't working like how you think it is (I suspect): single quotes [make a string literal](https://sqlite.org/lang_keywords.html), which is not a valid way to reference a column (you would need to use double quotes or grave accents to indicate an identifier). This means that query isn't doing anything with the columns, it is just comparing two string literals.

I think generally speaking, it would make sense for us to do some more in-depth query validation prior to execution of the query. This functionality is [all housed in the framework](https://github.com/qiime2/qiime2/blob/master/qiime2/metadata.py#L227-L292), so it probably makes the most sense to [continue this discussion there](https://github.com/qiime2/qiime2/issues/353)! Thanks!

**Comment by thermokarst** [comment]
I forgot to include the fixed up query in my reply above:

```bash
(q2dev-2017.9) ☁  moving-pictures  qiime feature-table filter-samples \
   --m-metadata-file sample-metadata.tsv \
   --i-table  table.qza \
   --p-where "this_doesnt_exist = 'FALSE'" \
   --o-filtered-table out.qza --verbose
Traceback (most recent call last):
  File "/Users/matthew/caporaso/qiime2/qiime2/qiime2/metadata.py", line 284, in ids
    c.execute(query)
sqlite3.OperationalError: no such column: this_doesnt_exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/matthew/caporaso/qiime2/q2cli/q2cli/commands.py", line 218, in __call__
    results = action(**arguments)
  File "<decorator-gen-264>", line 2, in filter_samples
  File "/Users/matthew/caporaso/qiime2/qiime2/qiime2/sdk/action.py", line 201, in callable_wrapper
    output_types, provenance)
  File "/Users/matthew/caporaso/qiime2/qiime2/qiime2/sdk/action.py", line 334, in _callable_executor_
    output_views = callable(**view_args)
  File "/Users/matthew/caporaso/qiime2/q2-feature-table/q2_feature_table/_filter.py", line 73, in filter_samples
    where=where, axis='sample', exclude_ids=exclude_ids)
  File "/Users/matthew/caporaso/qiime2/q2-feature-table/q2_feature_table/_filter.py", line 46, in _filter_table
    ids_to_keep = metadata.ids(where=where)
  File "/Users/matthew/caporaso/qiime2/qiime2/qiime2/metadata.py", line 288, in ids
    % query)
ValueError: Selection of IDs failed with query:
 SELECT "#SampleID" FROM metadata WHERE this_doesnt_exist = 'FALSE' GROUP BY "#SampleID" ORDER BY "#SampleID";

Plugin error from feature-table:

  Selection of IDs failed with query:  SELECT "#SampleID" FROM metadata
  WHERE this_doesnt_exist = 'FALSE' GROUP BY "#SampleID" ORDER BY
  "#SampleID";

See above for debug info.
```

Note the warning about a non-existent column: `sqlite3.OperationalError: no such column: this_doesnt_exist`

**Comment by antgonza** [comment]
Ha,  didn't see the example until now, check:
```bash
$ qiime feature-table filter-samples \
>    --m-metadata-file sample-metadata.tsv \
>    --i-table  table.qza \
>    --p-where '"this_doesnt_exist" == "FALSE"' \
>    --o-filtered-table out.qza
Saved FeatureTable[Frequency] to: out.qza

```
