### ISSUE TITLE
filter-features demands metadata map, even though it is optional

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-feature-table#52]
I see in the help menu that a metadata map is optional:
``--m-feature-metadata-file PATH  Metadata mapping file  [optional]``

However, if I attempt to run without a map specified I get the following error (full error below):
``OSError: Metadata file None doesn't exist or isn't accessible (e.g., due to incompatible file permissions).``

Full command and error:
```
$ qiime feature-table filter-features --i-table $projectdir/table.qza 
--o-filtered-table $projectdir/picrust/table.filter.qza --p-min-frequency 10 
--p-min-samples 3

Traceback (most recent call last):
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/qiime-2.0.5-py3.5.egg/qiime/metadata.py", line 25, in load
    df = pd.read_csv(path, sep='\t', dtype=object)
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/pandas/io/parsers.py", line 645, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/pandas/io/parsers.py", line 388, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/pandas/io/parsers.py", line 729, in __init__
    self._make_engine(self.engine)
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/pandas/io/parsers.py", line 922, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/pandas/io/parsers.py", line 1389, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4019)
  File "pandas/parser.pyx", line 683, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8144)
OSError: Expected file path name or file-like object, got <class 'NoneType'> type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/bin/qiime", line 6, in <module>
    sys.exit(q2cli.__main__.qiime())
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/q2cli-0.0.5-py3.5.egg/q2cli/commands.py", line 181, in __call__
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/q2cli-0.0.5-py3.5.egg/q2cli/commands.py", line 231, in handle_in_params
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/q2cli-0.0.5-py3.5.egg/q2cli/handlers.py", line 297, in get_value
  File "/Users/nbokulich/miniconda3/envs/qiime2-05/lib/python3.5/site-packages/qiime-2.0.5-py3.5.egg/qiime/metadata.py", line 30, in load
    "due to incompatible file permissions)." % path)
OSError: Metadata file None doesn't exist or isn't accessible (e.g., due to incompatible file permissions).
```

**Comment by gregcaporaso** [comment]
@nbokulich, this was [fixed in q2cli](https://github.com/qiime2/q2cli/pull/93). Can you pull down the latest version of q2cli and let us know if this is still an issue? If it's sorted out, can you close this issue? Thanks!

**Comment by nbokulich** [comment]
Ah, yes, sorry —  I had not updated q2cli. Closing now.

**Comment by gregcaporaso** [comment]
Thanks again!

On Thu, Nov 3, 2016 at 12:39 PM, Nicholas Bokulich <notifications@github.com
